***Будущий объект Future***.
Объект `asyncio.Future()` содержит одно значение, которое мы ожидаем получить, но, возможно, до сих пор не получили. Таким образом, объект `asyncio.Future()` существует - но он может быть без значения. Объект без значения называют ***неполным***. 
Чтобы объект стал ***полным***, если необходимо присвоить значение. Операции с объектом `asyncio.Future()`: 
1. `asyncio.Future().set_result(value)` - назначает значение объекту и делает его полным.
2. `asyncio.Future().done()` - проверяет, полный ли объект. 
3. `asyncio.Future().result()` - извлекает значение объекта. Если объекту не назначено значение, последует исключение `asyncio.InvalidStateError`. 
4. `asyncio.Future().set_exception(Exception)` - позволяет назначить объекту исключение заместо значения. В таком случае, если попытаться вызвать значение объекта, то возникнет назначенное исключение. 

Для будущих объектов класса `asyncio.Future` можно использовать конструкцию `await`. Она будет ждать до тех пор, пока объекту не будет назначено какое-либо значение. 

***Связь между будущими объектами, задачами и сопрограммами***.
Связь между объектами `asyncio` представлена следующим образом. 
![[Pasted image 20230116173703.png]]
`Task` напрямую наследует от `Future`. Можно считать, что `Future` представляет значение, которое появится в будущем. А `Task` представляет собой комбинацию `Future` и `Coroutine`. Создавая `Task` мы создаем пустой объект `Future` и запускаем `Coroutine`. 




___
```
from asyncio import Future

future = Future()
future.done() # False
future.result() #InvalidStateError
future.set_result(42)
future.done() # True
future.result() # 42



```

___
Relations: [[asyncio Python]] 
Tags: #code 
References: [[Asyncio (книга)]] 
Query: 